# Generated by Django 4.2.17 on 2024-12-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_puzzlesubmission_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
